version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=784915
      - DB=entrega
      - DB_USER=carla
      - SECRET_KEY=TESTE123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=carla
      - POSTGRES_PASSWORD=784915
      - POSTGRES_DB=entrega
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carla -d entrega"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
